baseURL: https://CalixTang.github.io/
languageCode: en-us
title: Calix Tang
theme: ["PaperMod"]


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Calix's Website
  description: "My Website"
  keywords: [Blog, Portfolio]
  author: Calix Tang
  # author: ["Me", "You"] # multiple authors
  images: []
  # DateFormat: "June 1, 2024"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  # ShareButtons: ["linkedin", "twitter"]
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  enableEmoji: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  #enable katex
  math: true

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my website. I'm using this page as a place to put my interests, hobbies, and projects as well as work on my writing!
  
  socialIcons:
    - name: "github"
      url: "https://github.com/CalixTang"
    - name: "youtube"
      url: "https://www.youtube.com/@calix-tang"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/calix-tang/"
  
  taxonomies:
    genre: genres
    tag: tags

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 40 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true #this allows the markdown renderer to inject html tags directly. could be unsafe.
  highlight:
    noClasses: false

menu:
  main:
    - identifier: archive
      name: archive
      url: /archives/
      weight: 10
    - identifier: search
      name: search
      url: /search/
      weight: 20
    - identifier: home
      name: home
      url: /
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

caches:
  maxAge: -1